apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
{{ toYaml .Values.global.labels | indent 4 }}

spec:
  type: {{ .Values.service.type }}

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP

  selector:
{{ toYaml .Values.global.labels | indent 4 }}
