apiVersion: v1
kind: Service
metadata:
  name: demo-web-app
  namespace: demo-dev
  labels:
    app: demo-web-app
    environment: dev
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: demo-web-app
